/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'zeyadelhodaiby' at '3/27/18 2:11 PM' with Gradle 2.14.1
 *
 * @author zeyadelhodaiby, @date 3/27/18 2:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
